### ISSUE TITLE
No CSS on new BelWue Webservers

### ISSUE THREAD

**Issue by ironiemix** [OpenSchulportfolio/openschulportfolio-build#3]
On the new BelWue webservers no css is displayed, when OSP is opened:
http://portfolio.teggingerschule.de/openschulportfolio/

Same effect shows with a vanilla DokuWiki (Greebo) - also no styles.
http://portfolio.teggingerschule.de/dokuwiki

PHP Version is  7.1.8, unfortunately I am no able to see the error logs on the servers. phpinfo():
http://portfolio.teggingerschule.de/pi.php

The newly created docker image with PHP 7.3.3 works fine:
https://github.com/linuxmuster-ext-docker/linuxmuster-osp-image

Do you have any ideas on this, @splitbrain ?

**Comment by splitbrain** [comment]
Hard to tell without logs. lib/exe/css.php output seems relatively short might be a fatal error while compiling the CSS. Maybe disable the `còmpress` option to see where it fails?

**Comment by ironiemix** [comment]
According to the BelWue webmaster the reason is, that ``parse_ini_file`` is disabled in PHP on BelWue. They want to enable the function, so let's wait on this and test again.

**Comment by splitbrain** [comment]
Yeah, I overlooked that in the phpinfo output. parse_ini_file should be the only problematic one in the list of disabled functions. At least for the standard dokuwiki setup. Some plugins might rely on calling external tools through system or proc_open.

**Comment by ironiemix** [comment]
Could anyone with an OSP Installation at BelWue please confirm that this is fixed. The BelWue Admins promised to do so...

**Comment by ironiemix** [comment]
Closing this - never heard back :(
